name: CI/CD Development
on :
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: auto deploy
    runs-on: ubuntu-latest

    steps:
    - name: get latest code
      uses: actions/checkout@v3

    - name : build
      run: |
        npm install
        npm run build

    - name: FTP DEPLOY
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: kaitodecode.com
        ftp_username: adi@kaitodecode.com
        ftp_password: 6DZSEJVnd7E1231231
        local_source_dir: "out"
        dist_target_dir: "./"
        delete: "true"
        exclude: "'^logs/' '^README.md'"  
